apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-helm
  namespace: argocd
spec:
  source:
    path: helm-dependency
    repoURL: https://github.com/s50600822/argocd-example-apps.git
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  project: default
