apiVersion: v1
kind: LimitRange
metadata:
  name: container-limits
spec:
  limits:
  - max:
      cpu: "125m"
      memory: "128Mi"
    min:
      cpu: "50m"
      memory: "64Mi"
    default:
      cpu: "125m"
      memory: "128Mi"
    defaultRequest:
      cpu: "75m"
      memory: "64Mi"
    type: Container
