apiVersion: apps/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: v1.peladonerd.local 
    http:
      paths:
      - backend:
          serviceName: hello-v1-svc
          servicePort: 80
  - host: v2.peladonerd.local
    http:
      paths:
      - backend:
          serviceName: hello-v2-svc
          servicePort: 80
