apiVersion: batch/v1
kind: Job
metadata:
  name: job-rabbit
spec:
  completions: 8
  parallelism: 2
  template:
    metadata:
      name: job-rabbit
    spec:
      containers:
      - name: c
        image: pablokbs/python-rabbitmq
        env:
        - name: BROKER_URL
          value: amqp://guest:guest@rabbitmq-service:5672
        - name: QUEUE
          value: job1
      restartPolicy: OnFailure
