apiVersion: batch/v1
kind: Job
metadata:
  name: job-redis
spec:
  parallelism: 2
  template:
    metadata:
      name: job-redis
    spec:
      containers:
      - name: c
        image: pablokbs/python-redis
      restartPolicy: OnFailure
