apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      metric:
        name: rabbitmq_queue_messages_ready
      describedObject:
        apiVersion: v1
        kind: Service
        name: rabbitmq-service
      target:
        type: Value
        value: 5
